package com.sample;
import com.saiful.phdprocess.*;
import org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl;
import org.kie.api.task.TaskService;

global TaskService taskService;

rule MyRule
  when
        WorkflowProcessInstanceImpl($readiness: variables['readiness'] == "ok")
  then
    System.out.println(">>>>>>>>>>>>>> from BR -> "+$readiness);
    //taskService.addTask();

    
end